# .coderabbit.yaml
# CodeRabbit Configuration - customized for Korean expert-style review

# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
language: "ko-KR"              # 리뷰 언어를 한국어로 설정
tone_instructions: "전문가스럽게 말할 것"  # 말투 지침
early_access: false
enable_free_tier: true

# =============================================================================
# REVIEWS
# =============================================================================
reviews:
  profile: "assertive"         # 꼼꼼한 리뷰 성향
  request_changes_workflow: true  # 문제 해결 전 merge 불가
  high_level_summary: true     # PR 전체 요약 생성
  high_level_summary_placeholder: "@coderabbitai summary" # 본문 내 요약 키워드
  review_status: true          # 리뷰 진행 상태 표시
  collapse_walkthrough: true   # 리뷰 결과 접기 기능
  changed_files_summary: true  # 변경된 파일 요약
  sequence_diagrams: true      # 시퀀스 다이어그램 생성
  estimate_code_review_effort: true  # 리뷰 난이도 표시
  auto_apply_labels: true      # 라벨 자동 적용

  auto_review:                 # 자동 리뷰 활성화
    enabled: true
    auto_incremental_review: true
    drafts: false

# =============================================================================
# KNOWLEDGE BASE
# =============================================================================
knowledge_base:
  opt_out: false               # 저장 기능 활성화
  web_search:
    enabled: true              # 외부 웹 검색 허용
  learnings:
    scope: "auto"              # 학습 범위 자동 선택
  issues:
    scope: "auto"
  pull_requests:
    scope: "auto"